//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid ScanForEntities = new Guid("e2e168f6-d5c6-4fc1-9b79-49a3128e67b7");
		public static readonly Guid TestAI = new Guid("b91b31d1-d1a9-4775-ad6f-b6453ffd8b53");

    }
}
